### ISSUE TITLE
Arabic search support

### ISSUE THREAD

**Issue by Y0usefmahdi** [aklein13/cp-clip#15]
Hey aklein13,
can you add the ability to search within the program in Arabic, for now the search only accept english words

**Comment by aklein13** [comment]
Will do. I wanted to add a support for every language for a while now

**Comment by Y0usefmahdi** [comment]
thanks bro, if you want any help with arabic language i'm here

**Comment by aklein13** [comment]
@Y0usefmahdi I think I got this working in the latest version 0.5.10 but I'm not sure how to type in Arabic.
Could you please test it and tell me how it works for you?

Some examples I have tried:
https://i.imgur.com/9HtDMNv.jpeg

**Comment by Y0usefmahdi** [comment]
It works like charm, thank you so much for your efforts
