### ISSUE TITLE
Add the ability to cleanup according to time

### ISSUE THREAD

**Issue by Y0usefmahdi** [aklein13/cp-clip#18]
Can you add the ability to clean according to time?

For example, if you want to erase all records that are 1 month old, or 2 months old, or as long as I specify, not just duplicate or large records, all old records that I won't use now...

**Comment by Y0usefmahdi** [comment]
@aklein13 any news Arkadiusz?

**Comment by aklein13** [comment]
@Y0usefmahdi Sorry I forgot about this issue. Yes I'll work on it on weekend/next week.

**Comment by aklein13** [comment]
@Y0usefmahdi New version with a cleanup window just got realeased. Now you can select desired cleanup methods along with old entries (date specified by you).
![2022-01-24_17-34-11_cp-clip](https://user-images.githubusercontent.com/16203517/150824748-613b8bb8-a19e-40a5-8fbd-23a1d2bb9fb9.jpg)

I'll edit the styling a bit soon but it's fully functional right now.

**Comment by Y0usefmahdi** [comment]
I've tried hundreds of clipboard managers, and this is literally the best and most powerful program I've ever used.

Thank you for your efforts in releasing this powerful update
You are a creative person, keep it up my friend

**Comment by Y0usefmahdi** [comment]
I've tried hundreds of clipboard managers, and this is literally the best and most powerful program I've ever used.

I switched from Mac to Windows recently, and I tried to find a program as powerful as Paste, but I never found it
If you can do it like its features or close to its design that would be great
https://pasteapp.io/

Thank you for your efforts in releasing this powerful update
You are a creative person, keep it up my friend
